package main

import (
	"path/filepath"
	"testing"
)

func TestLogsHelpers(t *testing.T) {
	t.Run("getLevel", func(t *testing.T) {
		tests := []struct {
			name    string
			message string
			want    string
		}{
			{
				name:    "backgrounder log with INFO",
				message: "2022-07-28 13:41:28.862 +0000 (,,,,,,) scheduled-background-job-runner-1 backgrounder: INFO  com.tableausoftware.model.workgroup.service.BackgroundJobService - find next pending job by job rank result jobId=3737369|progress=-1|createdAt=\\\"2022-07-28 13:41:28.318\\\"|startedAt=\\\"null\\\"|updatedAt=\\\"2022-07-28 13:41:28.318\\\"|finishCode=ERROR|lockVersion=0|backgrounderId=\\\"localhost:1:0\\\"|correlationId=null|serialId=null",
				want:    "info",
			},
			{
				name:    "valid JSON with sev field",
				message: `{"sev":"info","msg":"test message"}`,
				want:    "info",
			},
			{
				name:    "valid JSON with warn severity",
				message: `{"sev":"warn","msg":"warning message"}`,
				want:    "warn",
			},
			{
				name:    "valid JSON with error severity",
				message: `{"sev":"error","msg":"error message"}`,
				want:    "error",
			},
			{
				name:    "JSON with empty sev value",
				message: `{"sev":""}`,
				want:    "",
			},
			{
				name:    "JSON with single char sev value",
				message: `{"sev":"i"}`,
				want:    "i",
			},
			{
				name:    "JSON with debug severity",
				message: `{"sev":"debug","timestamp":"2024-01-01"}`,
				want:    "debug",
			},
			{
				name:    "empty message",
				message: "",
				want:    "",
			},
			{
				name:    "non-JSON message with INFO",
				message: "INFO: this is a log message",
				want:    "info",
			},
			{
				name:    "JSON without sev field",
				message: `{"msg":"test message","level":"debug"}`,
				want:    "",
			},
			{
				name:    "malformed JSON with truncated field",
				message: `{"sev":"}`,
				want:    "",
			},
			{
				name:    "truncated sev field in second JSON object",
				message: `{"other":"value"} {"sev":"}`,
				want:    "",
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				got := getLevel(tt.message)
				if got != tt.want {
					t.Errorf("getLevel(%q) = %q, want %q", tt.message, got, tt.want)
				}
			})
		}
	})
	t.Run("test getting process instance details from file paths", func(t *testing.T) {
		files := []struct {
			path      string
			process   string
			id        uint8
			component string
		}{
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activationservice/activationservice_node1-3.log", "activationservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activationservice/activationservice_node1-3.log.2022-07-30", "activationservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activationservice/activationservice-discovery_node1-3.log", "activationservice", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activationservice/activationservice-metrics_node1-3.log", "activationservice", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activationservice/control_activationservice_node1-3.log", "activationservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activationservice/nativeapi_activationservice_node1-3_2022_07_30_00_00_00.txt", "activationservice", 3, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activationservice/stdout_activationservice_5.log", "activationservice", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activemqserver/control_activemqserver_node1-3.log", "activemqserver", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/activemqserver/stdout_activemqserver_5.log", "activemqserver", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/allegro/allegro_node1-3.log", "allegro", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/allegro/allegro_node1-3.log.2022-07-29", "allegro", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/allegro/allegro-discovery_node1-3.log", "allegro", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/allegro/allegro-metrics_node1-3.log", "allegro", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/allegro/control_allegro_node1-3.log", "allegro", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/allegro/stdout_allegro_5.log", "allegro", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/allegro/tomcat_allegro_access_node1-3.2022-08-04.log", "allegro", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/allegro/tomcat_allegro_node1-3.2022-07-30.log", "allegro", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/analyticsextensions/analyticsextensions_node1-3.log", "analyticsextensions", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/analyticsextensions/analyticsextensions_node1-3.log.2022-07-29", "analyticsextensions", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/analyticsextensions/analyticsextensions-discovery_node1-3.log", "analyticsextensions", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/analyticsextensions/analyticsextensions-metrics_node1-3.log", "analyticsextensions", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/analyticsextensions/control_analyticsextensions_node1-3.log", "analyticsextensions", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/analyticsextensions/stdout_analyticsextensions_5.log", "analyticsextensions", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/analyticsextensions/tomcat_analyticsextensions_access_node1-3.2022-08-04.log", "analyticsextensions", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/analyticsextensions/tomcat_analyticsextensions_node1-3.2022-07-30.log", "analyticsextensions", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/apigateway/apigateway_node1-3.log", "apigateway", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/apigateway/apigateway_node1-3.log.2022-07-29", "apigateway", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/apigateway/apigateway-metrics_node1-3.log", "apigateway", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/apigateway/control_apigateway_node1-3.log", "apigateway", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/apigateway/stdout_apigateway_5.log", "apigateway", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/apigateway/tomcat_apigateway_access_node1-3.2022-08-04.log", "apigateway", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/apigateway/tomcat_apigateway_node1-3.2022-07-30.log", "apigateway", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/appzookeeper/appzookeeper_node1-3.log", "appzookeeper", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/appzookeeper/appzookeeper_node1-3.log.2022-07-30", "appzookeeper", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/appzookeeper/appzookeeper-discovery_node1-3.log", "appzookeeper", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/appzookeeper/appzookeeper-metrics_node1-3.log", "appzookeeper", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/appzookeeper/control_appzookeeper_node1-3.log", "appzookeeper", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/appzookeeper/stdout_appzookeeper_5.log", "appzookeeper", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/authnservice/authnservice_node1-3.log", "authnservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/authnservice/authnservice_node1-3.log.2022-07-29", "authnservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/authnservice/authnservice-discovery_node1-3.log", "authnservice", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/authnservice/authnservice-metrics_node1-3.log", "authnservice", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/authnservice/control_authnservice_node1-3.log", "authnservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/authnservice/stdout_authnservice_5.log", "authnservice", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/authnservice/tomcat_authnservice_access_node1-3.2022-08-04.log", "authnservice", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/authnservice/tomcat_authnservice_node1-3.2022-07-30.log", "authnservice", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/backgrounder_node1-3.log", "backgrounder", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/backgrounder_node1-3.log.2022-07-30", "backgrounder", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/backgrounder-instrumentation-metrics_node1-3.log", "backgrounder", 3, "instrumentation-metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/backgrounder-instrumentation-metrics_node1-3.log.2022-07-29", "backgrounder", 3, "instrumentation-metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/backgrounder-metrics_node1-3.log", "backgrounder", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/control_backgrounder_node1-3.log", "backgrounder", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/nativeapi_backgrounder_1-9_2022_07_30_00_00_00.txt", "backgrounder", 9, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/stdout_backgrounder_5.log", "backgrounder", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/stdout_oauthservice_backgrounder_1-7.txt", "backgrounder", 7, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/tomcat_backgrounder_access_node1-3.2022-08-04.log", "backgrounder", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/tomcat_backgrounder_node1-3.2022-07-29.log", "backgrounder", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/backuprestore_node1-3.log", "backuprestore", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/backuprestore_node1-3.log.2022-07-30", "backuprestore", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/backuprestore-discovery_node1-3.log", "backuprestore", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/backuprestore-discovery_node1-3.log.2022-07-30", "backuprestore", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/backuprestore-metrics_node1-3.log", "backuprestore", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/backuprestore-metrics_node1-3.log.2022-07-30-01", "backuprestore", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/control_backuprestore_node1-3.log", "backuprestore", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/control_backuprestore_node1-3.log.2022-07-30", "backuprestore", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backuprestore/stdout_backuprestore_5.log", "backuprestore", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/cacheserver/control_cacheserver_node1-3.log", "cacheserver", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/cacheserver/redis_5.log", "cacheserver", 5, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/cacheserver/stdout_cacheserver_5.log", "cacheserver", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clientfileservice/clientfileservice_node1-3.log", "clientfileservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clientfileservice/clientfileservice_node1-3.log.2022-07-30", "clientfileservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clientfileservice/clientfileservice-discovery_node1-3.log", "clientfileservice", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clientfileservice/clientfileservice-metrics_node1-3.log", "clientfileservice", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clientfileservice/control_clientfileservice_node1-3.log", "clientfileservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clientfileservice/stdout_clientfileservice_5.log", "clientfileservice", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clustercontroller/clustercontroller-metrics_node1-3.log", "clustercontroller", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clustercontroller/stdout_clustercontroller_5.log", "clustercontroller", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/collections/collections_node1-3.log", "collections", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/collections/collections_node1-3.log.2022-07-30", "collections", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/collections/collections-discovery_node1-3.log", "collections", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/collections/collections-metrics_node1-3.log", "collections", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/collections/control_collections_node1-3.log", "collections", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/collections/stdout_collections_5.log", "collections", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/collections/tomcat_collections_access_node1-3.2022-08-04.log", "collections", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/collections/tomcat_collections_node1-3.2022-07-30.log", "collections", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/contentexploration/contentexploration_node1-3.log", "contentexploration", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/contentexploration/contentexploration_node1-3.log.2022-07-30", "contentexploration", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/contentexploration/contentexploration-discovery_node1-3.log", "contentexploration", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/contentexploration/contentexploration-metrics_node1-3.log", "contentexploration", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/contentexploration/control_contentexploration_node1-3.log", "contentexploration", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/contentexploration/stdout_contentexploration_5.log", "contentexploration", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/contentexploration/tomcat_contentexploration_access_node1-3.2022-08-04.log", "contentexploration", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/contentexploration/tomcat_contentexploration_node1-3.2022-07-30.log", "contentexploration", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/control_databasemaintenance_node1-3.log", "databasemaintenance", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/control_databasemaintenance_node1-3.log.2022-07-30", "databasemaintenance", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/databasemaintenance_node1-3.log", "databasemaintenance", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/databasemaintenance_node1-3.log.2022-07-30", "databasemaintenance", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/databasemaintenance-discovery_node1-3.log", "databasemaintenance", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/databasemaintenance-metrics_node1-3.log", "databasemaintenance", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/stdout_databasemaintenance_5.log", "databasemaintenance", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/stdout_postgres_node1-3.2022-07-30.log", "databasemaintenance", 3, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/control_dataprofiling_node1-3.log", "dataprofiling", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/dataprofiling_node1-3.log", "dataprofiling", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/dataprofiling_node1-3.log.2022-07-30", "dataprofiling", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/dataprofiling-discovery_node1-3.log", "dataprofiling", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/metrics_node1-3.log", "dataprofiling", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/metrics_node1-3.log.2022-07-30", "dataprofiling", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/stdout_dataprofiling_5.log", "dataprofiling", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/tomcat_dataprofiling_access_node1-3.2022-08-04.log", "dataprofiling", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataprofiling/tomcat_dataprofiling_node1-3.2022-07-30.log", "dataprofiling", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/control_dataserver_node1-3.log", "dataserver", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/dataserver_node1-3.log", "dataserver", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/dataserver_node1-3.log.2022-07-30", "dataserver", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/dataserver-instrumentation-metrics_node1-3.log", "dataserver", 3, "instrumentation-metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/dataserver-instrumentation-metrics_node1-3.log.2022-07-30", "dataserver", 3, "instrumentation-metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/dataserver-metrics_node1-3.log", "dataserver", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/jprotocolserver_dataserver_1-7.log", "dataserver", 7, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/jprotocolserver_dataserver_1-9_2022_08_03.log", "dataserver", 9, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/nativeapi_dataserver_1-9_2022_07_30_00_00_00.txt", "dataserver", 9, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/stdout_dataserver_5.log", "dataserver", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/stdout_jprotocolserver_dataserver_1-7.txt", "dataserver", 7, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/stdout_oauthservice_dataserver_1-7.txt", "dataserver", 7, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/tabprotosrv_dataserver_1-9_2022_07_30_00_20_25.txt", "dataserver", 9, "tabprotosrv"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/tabprotosrv_dataserver_1-9_2022_07_30_22_43_34_1.txt", "dataserver", 9, "tabprotosrv"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/tabprotosrv_dataserver_1-9_2022_07_30_22_43_34_10.txt", "dataserver", 9, "tabprotosrv"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/tabprotosrv_dataserver_1-9_2022_07_30_22_43_34.txt", "dataserver", 9, "tabprotosrv"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/tomcat_dataserver_access_node1-3.2022-08-04.log", "dataserver", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/tomcat_dataserver_node1-3.2022-07-29.log", "dataserver", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/control_extractservice_node1-3.log", "extractservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/extractservice_node1-3.log", "extractservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/extractservice_node1-3.log.2022-07-30", "extractservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/extractservice-discovery_node1-3.log", "extractservice", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/metrics_node1-3.log", "extractservice", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/metrics_node1-3.log.2022-07-30", "extractservice", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/stdout_extractservice_5.log", "extractservice", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/tomcat_extractservice_access_node1-3.2022-08-04.log", "extractservice", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/extractservice/tomcat_extractservice_node1-3.2022-07-30.log", "extractservice", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/filestore/control_filestore_node1-3.log", "filestore", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/filestore/control_filestore_node1-3.log.2022-07-30", "filestore", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/filestore/filestore-metrics_node1-3.log", "filestore", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/filestore/stdout_filestore_5.log", "filestore", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/floweditor/control_floweditor_node1-3.log", "floweditor", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/floweditor/floweditor_node1-3.log", "floweditor", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/floweditor/floweditor_node1-3.log.2022-07-30", "floweditor", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/floweditor/floweditor-discovery_node1-3.log", "floweditor", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/floweditor/floweditor-metrics_node1-3.log", "floweditor", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/floweditor/stdout_floweditor_5.log", "floweditor", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/floweditor/tomcat_floweditor_access_node1-3.2022-08-04.log", "floweditor", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/floweditor/tomcat_floweditor_node1-3.2022-07-30.log", "floweditor", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowminerva/control_flowminerva_node1-3.log", "flowminerva", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowminerva/control_flowminerva_node1-3.log.2022-07-31", "flowminerva", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowminerva/nativeapi_flowminerva_node1-3_2022_07_30_00_00_00.txt", "flowminerva", 3, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowminerva/stdout_flowminerva_5.log", "flowminerva", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/control_flowprocessor_node1-3.log", "flowprocessor", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/flowprocessor_node1-3.log", "flowprocessor", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/flowprocessor_node1-3.log.2022-07-30", "flowprocessor", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/flowprocessor-discovery_node1-3.log", "flowprocessor", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/flowprocessor-metrics_node1-3.log", "flowprocessor", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/stdout_flowprocessor_5.log", "flowprocessor", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/tomcat_flowprocessor_access_node1-3.2022-08-04.log", "flowprocessor", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/tomcat_flowprocessor_node1-3.2022-07-30.log", "flowprocessor", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/httpd/control_gateway_node1-3.log", "gateway", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/httpd/gateway-metrics_node1-3.log", "gateway", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/httpd/stdout_gateway_5.log", "gateway", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/hyper/control_hyper_node1-3.log", "hyper", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/hyper/hyper_0_2022_07_30_00_00_00.log", "hyper", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/hyper/stdout_hyper_5.log", "hyper", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/indexandsearchserver/control_indexandsearchserver_node1-3.log", "indexandsearchserver", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/indexandsearchserver/stdout_indexandsearchserver_5.log", "indexandsearchserver", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/interactive/control_interactive_node1-3.log", "interactive", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/interactive/interactive_node1-3.log", "interactive", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/interactive/interactive_node1-3.log.2022-07-30", "interactive", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/interactive/interactive-discovery_node1-3.log", "interactive", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/interactive/interactive-metrics_node1-3.log", "interactive", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/interactive/stdout_interactive_5.log", "interactive", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/interactive/tomcat_interactive_access_node1-3.2022-08-04.log", "interactive", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/interactive/tomcat_interactive_node1-3.2022-07-30.log", "interactive", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/licenseservice/control_licenseservice_node1-3.log", "licenseservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/licenseservice/stdout_licenseservice_5.log", "licenseservice", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/metrics/control_metrics_node1-3.log", "metrics", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/metrics/metrics_node1-3.log", "metrics", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/metrics/metrics_node1-3.log.2022-07-30", "metrics", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/metrics/metrics-discovery_node1-3.log", "metrics", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/metrics/metrics-metrics_node1-3.log", "metrics", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/metrics/stdout_metrics_5.log", "metrics", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/metrics/tomcat_metrics_access_node1-3.2022-08-04.log", "metrics", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/metrics/tomcat_metrics_node1-3.2022-07-30.log", "metrics", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/minerva/control_minerva_node1-3.log", "minerva", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/minerva/control_minerva_node1-3.log.2022-07-31", "minerva", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/minerva/nativeapi_minerva_node1-3_2022_07_30_00_00_00.txt", "minerva", 3, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/minerva/stdout_minerva_5.log", "minerva", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/nlp/control_nlp_node1-3.log", "nlp", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/nlp/control_nlp_node1-3.log.2022-07-31", "nlp", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/nlp/stdout_nlp_5.log", "nlp", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/noninteractive/control_noninteractive_node1-3.log", "noninteractive", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/noninteractive/noninteractive_node1-3.log", "noninteractive", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/noninteractive/noninteractive_node1-3.log.2022-07-30", "noninteractive", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/noninteractive/noninteractive-discovery_node1-3.log", "noninteractive", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/noninteractive/noninteractive-metrics_node1-3.log", "noninteractive", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/noninteractive/stdout_noninteractive_5.log", "noninteractive", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/noninteractive/tomcat_noninteractive_access_node1-3.2022-08-04.log", "noninteractive", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/noninteractive/tomcat_noninteractive_node1-3.2022-07-30.log", "noninteractive", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/control_pgsql_node1-3.log", "pgsql", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/control_pgsql_node1-3.log.2022-07-30", "pgsql", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/control_publishedconnections_node1-3.log", "publishedconnections", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/metrics_node1-3.log", "publishedconnections", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/metrics_node1-3.log.2022-07-30", "publishedconnections", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/publishedconnections_node1-3.log", "publishedconnections", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/publishedconnections_node1-3.log.2022-07-30", "publishedconnections", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/publishedconnections-discovery_node1-3.log", "publishedconnections", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/stdout_publishedconnections_5.log", "publishedconnections", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/tomcat_publishedconnections_access_node1-3.2022-08-04.log", "publishedconnections", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/publishedconnections/tomcat_publishedconnections_node1-3.2022-07-30.log", "publishedconnections", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/control_querygateway_node1-3.log", "querygateway", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/metrics_node1-3.log", "querygateway", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/metrics_node1-3.log.2022-07-30", "querygateway", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/querygateway_node1-3.log", "querygateway", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/querygateway_node1-3.log.2022-07-30", "querygateway", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/querygateway-discovery_node1-3.log", "querygateway", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/stdout_querygateway_5.log", "querygateway", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/tomcat_querygateway_access_node1-3.2022-08-04.log", "querygateway", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querygateway/tomcat_querygateway_node1-3.2022-07-30.log", "querygateway", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/control_querypolicy_node1-3.log", "querypolicy", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/metrics_node1-3.log", "querypolicy", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/metrics_node1-3.log.2022-07-30", "querypolicy", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/querypolicy_node1-3.log", "querypolicy", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/querypolicy_node1-3.log.2022-07-30", "querypolicy", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/querypolicy-discovery_node1-3.log", "querypolicy", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/stdout_querypolicy_5.log", "querypolicy", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/tomcat_querypolicy_access_node1-3.2022-08-04.log", "querypolicy", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/querypolicy/tomcat_querypolicy_node1-3.2022-07-30.log", "querypolicy", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/samlservice/control_samlservice_node1-3.log", "samlservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/searchserver/control_searchserver_node1-3.log", "searchserver", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/searchserver/searchserver-7.log", "searchserver", 7, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/searchserver/searchserver-7.log.2022-07-30", "searchserver", 7, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/searchserver/stdout_searchserver_5.log", "searchserver", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/siteimportexport/control_siteimportexport_node1-3.log", "siteimportexport", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/statsservice/control_statsservice_node1-3.log", "statsservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/statsservice/control_statsservice_node1-3.log.2022-07-31", "statsservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/statsservice/stdout_statsservice_5.log", "statsservice", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadminagent/control_tabadminagent_node1-3.log", "tabadminagent", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadminagent/stdout_tabadminagent_5.log", "tabadminagent", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadminagent/tabadminagent_node1-3.log", "tabadminagent", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadminagent/tabadminagent_node1-3.log.2022-07-30", "tabadminagent", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadminagent/tabadminagent-discovery_node1-3.log", "tabadminagent", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadminagent/tabadminagent-discovery_node1-3.log.2022-07-29", "tabadminagent", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadminagent/tabadminagent-metrics_node1-3.log", "tabadminagent", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadminagent/tabadminagent-metrics_node1-3.log.2022-07-30-00", "tabadminagent", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/control_tabadmincontroller_node1-3.log", "tabadmincontroller", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/nativeapi_tabadmincontroller_node1-3_2022_07_29_00_00_00.txt", "tabadmincontroller", 3, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/stdout_tabadmincontroller_5.log", "tabadmincontroller", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/tabadmincontroller_node1-3.log", "tabadmincontroller", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/tabadmincontroller_node1-3.log.2022-07-30", "tabadmincontroller", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/tabadmincontroller-discovery_node1-3.log", "tabadmincontroller", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/tabadmincontroller-discovery_node1-3.log.2022-07-30", "tabadmincontroller", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/tabadmincontroller-metrics_node1-3.log", "tabadmincontroller", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/tabadmincontroller-metrics_node1-3.log.2022-07-30-01", "tabadmincontroller", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsnativeservice/control_tdsnativeservice_node1-3.log", "tdsnativeservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsnativeservice/control_tdsnativeservice_node1-3.log.2022-07-31", "tdsnativeservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsnativeservice/stdout_tdsnativeservice_5.log", "tdsnativeservice", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsservice/control_tdsservice_node1-3.log", "tdsservice", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsservice/stdout_tdsservice_5.log", "tdsservice", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsservice/tdsservice_node1-3.log", "tdsservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsservice/tdsservice_node1-3.log.2022-07-30", "tdsservice", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsservice/tdsservice-metrics_node1-3.log", "tdsservice", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsservice/tomcat_tdsservice_access_node1-3.2022-08-04.log", "tdsservice", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsservice/tomcat_tdsservice_node1-3.2022-07-30.log", "tdsservice", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/audit-history_node1-3.log", "vizportal", 3, "audit-history"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/control_vizportal_node1-3.log", "vizportal", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/nativeapi_vizportal_1-9_2022_07_30_00_00_00.txt", "vizportal", 9, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/stdout_vizportal_5.log", "vizportal", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/tomcat_vizportal_access_node1-3.2022-08-04.log", "vizportal", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/tomcat_vizportal_node1-3.2022-07-29.log", "vizportal", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/vizportal_node1-3.log", "vizportal", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/vizportal_node1-3.log.2022-07-30", "vizportal", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/vizportal-grpc-request_node1-3.log", "vizportal", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/vizportal-instrumentation-metrics_node1-3.log", "vizportal", 3, "instrumentation-metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/vizportal-instrumentation-metrics_node1-3.log.2022-07-30", "vizportal", 3, "instrumentation-metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizportal/vizportal-metrics_node1-3.log", "vizportal", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/control_vizqlserver_node1-3.log", "vizqlserver", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/nativeapi_vizqlserver_1-9_2022_07_30_00_00_00.txt", "vizqlserver", 9, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/stdout_oauthservice_vizqlserver_1-7.txt", "vizqlserver", 7, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/stdout_vizqlserver_5.log", "vizqlserver", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/tabprotosrv_vizqlserver_1-9_2022_07_30_22_37_49.txt", "vizqlserver", 9, "tabprotosrv"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/tomcat_vizqlserver_access_node1-3.2022-08-04.log", "vizqlserver", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/tomcat_vizqlserver_node1-3.2022-07-29.log", "vizqlserver", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/vizql-client-7.log", "vizqlserver", 7, "vizql-client"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/vizqlserver_node1-3.log", "vizqlserver", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/vizqlserver_node1-3.log.2022-07-30", "vizqlserver", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/vizqlserver-instrumentation-metrics_node1-3.log", "vizqlserver", 3, "instrumentation-metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/vizqlserver-instrumentation-metrics_node1-3.log.2022-07-30", "vizqlserver", 3, "instrumentation-metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/vizqlserver-metrics_node1-3.log", "vizqlserver", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/webhooks/control_webhooks_node1-3.log", "webhooks", 3, "control"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/webhooks/stdout_webhooks_5.log", "webhooks", 5, "stdout"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/webhooks/tomcat_webhooks_access_node1-3.2022-08-04.log", "webhooks", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/webhooks/tomcat_webhooks_node1-3.2022-07-30.log", "webhooks", 3, "tomcat"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/webhooks/webhooks_node1-3.log", "webhooks", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/webhooks/webhooks_node1-3.log.2022-07-30", "webhooks", 3, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/webhooks/webhooks-discovery_node1-3.log", "webhooks", 3, "discovery"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/webhooks/webhooks-metrics_node1-3.log", "webhooks", 3, "metrics"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/oauth-service.log", "backgrounder", 0, "oauth-service"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clustercontroller/clustercontroller.log", "clustercontroller", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/clustercontroller/clustercontroller.log.2022-07-30", "clustercontroller", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/41bc510d/postgresql-Wed.csv", "databasemaintenance", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/41bc510d/postgresql-Wed.log", "databasemaintenance", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/oauth-service_2022_08_03.log", "dataserver", 0, "oauth-service"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/dataserver/oauth-service.log", "dataserver", 0, "oauth-service"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/filestore/filestore.log", "filestore", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/filestore/filestore.log.2022-07-30", "filestore", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/flowprocessor/nativeapi_flowprocessor_2022_07_30_00_00_00.txt", "flowprocessor", 0, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/httpd/access.2022_07_29_00_00_00.log", "gateway", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/httpd/error.log", "gateway", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/httpd/gateway.log", "gateway", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/httpd/gateway.log.2022-07-30", "gateway", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/httpd/startup.log", "gateway", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/hyper/checklicense.log", "hyper", 0, "checklicense"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/hyper/checklicense.log.2022-07-30", "hyper", 0, "checklicense"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/hyper/nativeapi_checklicense_bk.txt", "hyper", 0, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/hyper/nativeapi_checklicense.txt", "hyper", 0, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/indexandsearchserver/opensearch_deprecation.log", "indexandsearchserver", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/indexandsearchserver/opensearch_index_indexing_slowlog.log", "indexandsearchserver", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/indexandsearchserver/opensearch_index_search_slowlog.log", "indexandsearchserver", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/indexandsearchserver/opensearch-2022-07-29-1.log.gz", "indexandsearchserver", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/indexandsearchserver/opensearch.log", "indexandsearchserver", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/licenseservice/tablicsrv.log", "licenseservice", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/cleanupOrphansCommand.log", "pgsql", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/pg_restore.log", "pgsql", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/postgresql-Fri.csv", "pgsql", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/postgresql-Fri.log", "pgsql", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/spawn.log", "pgsql", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/sql.log", "pgsql", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/searchserver/solr_gc.log", "searchserver", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/searchserver/solr_gc.log.0", "searchserver", 0, ""},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/tdsnativeservice/nativeapi_tdsnativeservice_2022_07_29_00_00_00.txt", "tdsnativeservice", 0, "nativeapi"},
			{"/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/oauth-service.log", "vizqlserver", 0, "oauth-service"},
		}
		for _, file := range files {
			gotProcess := getProcessName(file.path, `/var/opt/tableau/tableau_server/data/tabsvc/logs`)
			if gotProcess != file.process {
				t.Errorf("got process %s, wanted %s from %s", gotProcess, file.process, file.path)
			}
			filename := filepath.Base(file.path)
			gotId := getProcessId(filename)
			if gotId != file.id {
				t.Errorf("got id %d, wanted %d from %s", gotId, file.id, file.path)
			}
			gotComponent := getComponent(filename)
			if gotComponent != file.component {
				t.Errorf("got component %s, wanted %s from %s", gotComponent, file.component, file.path)
			}
		}
	})
}
